# Site settings
title:       杨军军的博客
email:       ggiiss@qq.com 
author:      杨军军
description: 专注于前端
baseurl:     ""
url:         ""

#Duoshuo short Name / 多说的shortname
duoshuo: xngiser

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze: 1cf66887502cd1bbc3e1ccba4ebd3d04 

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty

# Pls refer to http://jekyllrb.com/docs/pagination/
# Specifies how many items should be displayed per page
paginate:     3
sass:
  compressed: true
