markdown: redcarpet
#markdown: rdiscount
pygments: true
css-url: /css
permalink: /:year-:month-:day-:title.html
kramdown:
    extensions: ["fenced_code_blocks"]
    input: GFM

highlighter: pygments
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
