# 设置 Markdown 的渲染引擎，还可以是 rdiscount
markdown: redcarpet

pygments: true
highlighter: pygments
kramdown:
    extensions: ["fenced_code_blocks"]
    input: GFM
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
css-url: /css
permalink: /:year/:month/:day/:title.html



